### ISSUE TITLE
VW MQBevo: DBC header invalid

### ISSUE THREAD

**Issue by MonsterPerformance** [commaai/opendbc#1336]
https://github.com/commaai/opendbc/blame/67dbc3b1bf9051c8db1c8db6de1f2ad3bb7e668f/opendbc/dbc/vw_mqbevo.dbc#L1

**Comment by jyoung8607** [comment]
Your observation is correct, it's a work in progress from #906. This being my own work, I know it needs other fixes and cleanup as well. This won't be fixed immediately, but I'll keep it on my TODO list for when I get back to MQBevo sometime in the next few weeks.

For cars that aren't actually supported yet, we're trying to be a little more permissive about merging opendbc works in progress, so that car maintainers can iterate more easily without constantly having to deal with merge conflicts. This does not apply to Panda safety.

In the meantime I'd merge a PR to put placeholder headers on it, such that it becomes a semantically valid DBC that other tools can open. This goes for any other DBC, although I think our subset of generated DBCs would have to have the generator fixed first.
