### ISSUE TITLE
CAN_VERS in hyundai_kia_generic.dbc is incorrect

### ISSUE THREAD

**Issue by andresv** [commaai/opendbc#383]
https://github.com/commaai/opendbc/blob/master/hyundai_kia_generic.dbc#L1063
defines following signal
```
SG_ CAN_VERS m0 : 0|6@1+ (1.0,0.0) [0.0|7.7] ""  _4WD,ABS,ESC,IBOX
```
.. which must be incorrect, max cannot be `7.7` with such fraction and offset

**Comment by adeebshihadeh** [comment]
I'm going to close these inconsistencies are littered throughout the DBCs. In general, the min and max range values aren't super authoritative since we don't use them in openpilot. Ideally, we would have a small DBC parser to enforce stuff like this is consistent. Feel free to submit PRs for this stuff though.
